application: farkle
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /_ah/spi/.*
  script: api.api

libraries:
- name: webapp2
  version: latest

- name: endpoints
  version: latest
